platform :ios, "8.0"

target "INSPhotoGallery" do
    pod 'INSNibLoading'
    pod 'Kingfisher', :git => 'https://github.com/onevcat/Kingfisher.git', :branch => "swift3"
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "3.0"
        end
    end
end

use_frameworks!
